{{- if .Values.hook.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "globex-cdc.serviceAccountName" . }}-hook
  labels:
    {{- include "globex-cdc.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.argocd.enabled }}
    {{- include "globex-cdc.argocd-syncwave" . | nindent 4 }}
    {{- else }}
    "helm.sh/hook": pre-install  
    {{- end }}
{{- end }}
