apiVersion: console.streamshub.github.com/v1alpha1
kind: Console
metadata:
  name: {{ include "amq-streams-console.name" . }}
  {{- if .Values.namespace }}
  namespace: {{ .Values.namespace }}
  {{- end }}
  labels:
    {{- include "amq-streams-console.labels" . | nindent 4 }}
  annotations:
    {{- include "amq-streams-console.argocd-syncwave" . | nindent 4 }}
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  hostname: {{ .Values.hostName }}
  metricsSources:
    - name: ocp-prometheus
      type: openshift-monitoring
  kafkaClusters:
    - name: {{ .Values.kafka.name }}
      namespace: {{ include "kafka.namespace" . }}
      listener: {{ .Values.kafka.listener }}
      metricsSource: ocp-prometheus
      properties:
        values: []
        valuesFrom: []
{{- if eq .Values.kafka.authentication.saslMechanism "SCRAM-SHA-512" }}
      credentials:
        kafkaUser:
          name: {{ include "amq-streams-console.name" . }}-kafka-user
{{- end }}