{{- if eq .Values.persistence.mode "persistent" -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "service-registry-db.name" . }}
  namespace: {{ include "service-registry-db.namespace" . }}
  labels:
    {{- include "service-registry-db.labels" . | nindent 4 }}
  annotations:
    {{- include "service-registry-db.argocd-syncwave" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.capacity }}
{{- end }}