apiVersion: v1
kind: Service
metadata:
  name: {{ include "service-registry-db.name" . }}
  namespace: {{ include "service-registry-db.namespace" . }}
  labels:
    {{- include "service-registry-db.labels" . | nindent 4 }}
  annotations:
    {{- include "service-registry-db.argocd-syncwave" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: {{ .Values.service.portName }}
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.containerPort }}
  selector:
    {{- include "service-registry-db.selectorLabels" . | nindent 4 }}
