pgsql:
  service: service-registry-db
  database: apicurio
  user: apicurio
  password: apicurio

app:
  route:
    enabled: true
    host: 
    tlsEnabled: true
    tls:
      termination: edge
      insecureEdgeTerminationPolicy: Redirect
  ingress:
    enabled: false
  resources:
    limits:
      cpu: 250m
      memory: 512Mi
    requests:
      cpu: 125m
      memory: 512Mi
  livenessProbe:
    httpGet:
      path: /health/live
      port: 8080
      scheme: HTTP
    initialDelaySeconds: 30
    timeoutSeconds: 3
    periodSeconds: 10
    successThreshold: 1
    failureThreshold: 3

  readinessProbe:
    httpGet:
      path: /health/ready
      port: 8080
      scheme: HTTP
    initialDelaySeconds: 5
    timeoutSeconds: 3
    periodSeconds: 10
    successThreshold: 1
    failureThreshold: 3

ui:
  route:
    enabled: true
    host: 
    tlsEnabled: true
    tls:
      termination: edge
      insecureEdgeTerminationPolicy: Redirect
  ingress:
    enabled: false
  resources:
    limits:
      cpu: 250m
      memory: 512Mi
    requests:
      cpu: 125m
      memory: 512Mi

argocd:
  enabled: true
  syncwave: "0"
