kind: Secret
apiVersion: v1
metadata:
  name: {{ include "service-registry.name" . }}
  namespace: {{ include "service-registry.namespace" . }}
  labels:
    {{- include "service-registry.labels" . | nindent 4 }}
  annotations:
    {{- include "service-registry.argocd-syncwave" . | nindent 4 }}
stringData:
  password: {{ .Values.pgsql.password }}
type: Opaque
