nameOverride: "kafka"

kafka:
  version: 4.0.0
  metadataVersion: 4.0-IV3
  broker:
    replicas: 3
    storage:
      type: jbod
      volumes:
        - id: 0
          type: persistent-claim
          size: 10Gi
          deleteClaim: true
  controller:
    enabled: true
    replicas: 3
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 200M
    storage:
      type: jbod
      volumes:
        - id: 0
          type: persistent-claim
          size: 5Gi
          deleteClaim: true      
  config:
    autoCreateTopics: false
    defaultReplicationFactor: 3
    offsetsTopicReplicationFactor: 3
    transactionStateLogReplicationFactor: 3
    transactionStateLogMinIsr: 2
    minInsyncReplicas: 2
  listener:
    external:
      enabled: false
      type: route
      tls:
        secret:
          key:
            crt: tls.crt
            key: tls.key
          value:
            crt:
            key: 
  entityOperator:
    topicOperator:
      resources:
        limits:
          cpu: 500m
          memory: 500M
        requests:
          cpu: 250m
          memory: 250M
    userOperator:
      resources:
        limits:
          cpu: 250m
          memory: 250M
        requests:
          cpu: 150m
          memory: 150M
  resources:
    limits:
      cpu: '1'
      memory: 2G
    requests:
      cpu: 300m
      memory: 500M

namespace:

authentication: {}

authorization: simple

argocd:
  syncwave:
    enabled: true
    kafka: "0"
    namespace: "-1"
